### ISSUE TITLE
The build log is not visible

### ISSUE THREAD

**Issue by gengjiawen** [MicrosoftDocs/pipelines-xcode#1]
Also this repo looks like not do any actual build.
Click the build link from commit.

**Comment by willsmythe** [comment]
@gengjiawen - thanks for reporting. We will get this fixed.

In the meantime, if you are just looking to view the Azure Pipelines UX and any build results and logs, here are some examples:
https://dev.azure.com/vscode/VSCode/_build?definitionId=1
https://dev.azure.com/devongovett/devongovett/_build/results?buildId=384&view=logs

@DavidStaheli - the configured pipeline for this project appears to be looking for 'vsts-ci.yml' (I'm basing this on the commit history and lack of status updates after this file was renamed: https://github.com/MicrosoftDocs/pipelines-xcode/commits/master). Can you get this working again?
