### ISSUE TITLE
Need to migrate to Swift from 3.0 to 4.0 at least

### ISSUE THREAD

**Issue by arammaliachi** [MicrosoftDocs/pipelines-xcode#3]
This code is meant to show Azure DevOps (AzD onwards) users how an iOS app would compile using an Azure Pipeline out of the box. If we use the .yml given pipeline as is the build succeeds. 

The problem is if users prefer to implement a classic pipeline in AzD with the given classic pipelines the resulting pipeline would run in the mac-os10.14 by default causing the pipeline to throw an error as following if left as is.

`error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'iOSHelloWorld')`

The solution for this is to roll back the agent back to macos-10.13 **or** the xCode version to xCode 9 for classic pipelines.

I'd say the .yml file should also be changed to run in macOS-latest instead of macOS 10.13
I can submit the PR if that is ok

**Comment by cjazz** [comment]
I agree with aramaliachi, and further if this options intent is to get a higher adoption rate, macOS Catalina (currently at 10.15.2), and Xcode 11.2+, Swift Version 5 needs to be supported.

**Comment by shbadawy** [comment]
The problem is still happening

**Comment by meiry** [comment]
@shbadawy @cjazz @arammaliachi
Amazing Microsoft .. and the example doesn't work.
to fix this example go to :
iOSHelloWorld.xcodeproj/project.pbxproj
search replace all 
SWIFT_VERSION = 3.0;
to 
SWIFT_VERSION = 4.2;  
or 
SWIFT_VERSION = 5.0;

go to : 
iOSHelloWorld/AppDelegate.swift
change 
UIApplicationLaunchOptionsKey: Any
to ( There is dot "." ) 
UIApplication.LaunchOptionsKey: Any

commit all and it should build just fine 
![image](https://user-images.githubusercontent.com/1107316/91654100-e840ee80-eaae-11ea-9823-c224c9beae56.png)

**Comment by christian-becker-ta** [comment]
Great  meiry this fixxed the issue for me. 
@MS possible to update this repo?

**Comment by fran38** [comment]
[https://github.com/MicrosoftDocs/pipelines-xcode/issues/3#issuecomment-747950508]() ``
